version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress-files:/var/www/html
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress-files:/var/www/html
    restart: on-failure
    depends_on:
      - mariadb
      - redis
    networks:
      - inception

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress-database:/var/lib/mysql
    restart: on-failure
    networks:
      - inception

  redis:
    container_name: redis
    image: redis
    build:
      context: ./bonus/redis
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - inception

  ftp:
    container_name: ftp
    image: ftp
    build:
      context: ./bonus/ftp
      dockerfile: Dockerfile
      args:
        - FTP_USER
        - FTP_PASS
    ports:
      - "21:21"
      - "1024-1048:1024-1048"
    volumes:
      - wordpress-files:/var/www/html
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - inception

  adminer:
    container_name: adminer
    image: adminer
    build:
      context: ./bonus/adminer
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - inception

  dozzle:
    container_name: dozzle
    image: dozzle
    build:
      context: ./bonus/dozzle
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    networks:
      - inception

volumes:
  wordpress-files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUME_PATH}/wordpress
  wordpress-database:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOLUME_PATH}/mariadb

networks:
  inception:
    driver: bridge
